if(NOT DEFINED CEF_ARCHIVE OR "${CEF_ARCHIVE}" STREQUAL "")
    message(FATAL_ERROR "VOXELS_ENABLE_WEB_UI requires -DVOXELS_WEB_UI_CEF_ARCHIVE=<official CEF archive>. See ASSET_REQUESTS.md WEBUI-001.")
endif()
if(NOT DEFINED CEF_SHA256)
    message(FATAL_ERROR "VOXELS_ENABLE_WEB_UI requires a 64-character -DVOXELS_WEB_UI_CEF_SHA256=<archive SHA-256>.")
endif()
string(LENGTH "${CEF_SHA256}" CEF_SHA256_LENGTH)
if(NOT CEF_SHA256_LENGTH EQUAL 64 OR NOT "${CEF_SHA256}" MATCHES "^[0-9a-fA-F]+$")
    message(FATAL_ERROR "VOXELS_ENABLE_WEB_UI requires a 64-character -DVOXELS_WEB_UI_CEF_SHA256=<archive SHA-256>.")
endif()
if(NOT EXISTS "${CEF_ARCHIVE}")
    message(FATAL_ERROR "The configured CEF archive does not exist: '${CEF_ARCHIVE}'. Download it from the official CEF distribution and verify its SHA-256.")
endif()

file(SHA256 "${CEF_ARCHIVE}" actual_sha256)
if(NOT actual_sha256 STREQUAL CEF_SHA256)
    message(FATAL_ERROR "CEF archive SHA-256 mismatch. Expected ${CEF_SHA256}; got ${actual_sha256}. The archive will not be extracted.")
endif()
if(EXISTS "${CEF_RUNTIME_ROOT}/runtime-root.txt")
    file(READ "${CEF_RUNTIME_ROOT}/runtime-root.txt" existing_root)
    string(STRIP "${existing_root}" existing_root)
    if(EXISTS "${existing_root}")
        return()
    endif()
endif()
file(REMOVE_RECURSE "${CEF_RUNTIME_ROOT}")
file(MAKE_DIRECTORY "${CEF_RUNTIME_ROOT}")
file(ARCHIVE_EXTRACT INPUT "${CEF_ARCHIVE}" DESTINATION "${CEF_RUNTIME_ROOT}")
file(GLOB extracted_directories LIST_DIRECTORIES TRUE "${CEF_RUNTIME_ROOT}/cef_binary_*")
list(LENGTH extracted_directories directory_count)
if(NOT directory_count EQUAL 1)
    message(FATAL_ERROR "CEF archive must contain exactly one cef_binary_* root directory.")
endif()
list(GET extracted_directories 0 extracted_root)
file(WRITE "${CEF_RUNTIME_ROOT}/runtime-root.txt" "${extracted_root}")