if(NOT DEFINED MANIFEST_PATH OR NOT EXISTS "${MANIFEST_PATH}")
    message(FATAL_ERROR "Web UI build did not produce ui-manifest.json at '${MANIFEST_PATH}'.")
endif()
file(READ "${MANIFEST_PATH}" manifest_json)
string(JSON schema_version GET "${manifest_json}" schema_version)
if(NOT schema_version EQUAL 1)
    message(FATAL_ERROR "Web UI manifest schema_version must be 1.")
endif()
string(JSON entry_html GET "${manifest_json}" entry_html)
string(JSON asset_count LENGTH "${manifest_json}" assets)
if(asset_count EQUAL 0)
    message(FATAL_ERROR "Web UI manifest must declare at least its entry HTML asset.")
endif()
set(entry_found FALSE)
math(EXPR last_asset "${asset_count} - 1")
foreach(index RANGE ${last_asset})
    string(JSON asset_path MEMBER "${manifest_json}" assets ${index})
    string(JSON expected_sha GET "${manifest_json}" assets "${asset_path}" sha256)
    string(JSON expected_bytes GET "${manifest_json}" assets "${asset_path}" bytes)
    get_filename_component(manifest_directory "${MANIFEST_PATH}" DIRECTORY)
    set(full_path "${manifest_directory}/${asset_path}")
    if(NOT EXISTS "${full_path}")
        message(FATAL_ERROR "Web UI manifest asset is missing: ${asset_path}")
    endif()
    file(SIZE "${full_path}" actual_bytes)
    file(SHA256 "${full_path}" actual_sha)
    if(NOT actual_bytes EQUAL expected_bytes OR NOT actual_sha STREQUAL expected_sha)
        message(FATAL_ERROR "Web UI manifest verification failed for ${asset_path}.")
    endif()
    if(asset_path STREQUAL entry_html)
        set(entry_found TRUE)
    endif()
endforeach()
if(NOT entry_found)
    message(FATAL_ERROR "Web UI manifest entry_html is not declared in assets.")
endif()